name = "MixedLayerThermoclineDynamics"
uuid = "1d4a6882-6b5f-4564-9c28-3a65b9d963cb"
license = "MIT"
authors = ["Dhruv Bhagtani <Dhruv.Bhagtani@anu.edu.au>", "Navid C. Constantinou <navidcy@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
DocStringExtensions = "0.8"
OffsetArrays = "1.10"
julia = "^1.6"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "Coverage"]
